name: Automatic Release

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Get version
        id: package
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Create GitHub Release
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          gh release create v${{ steps.package.outputs.version }} --title "Release v${{ steps.package.outputs.version }}" --notes "Release notes for v${{ steps.package.outputs.version }}"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
  publish-npm:
      needs: [release, build]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 16
            registry-url: https://registry.npmjs.org/
        - run: npm ci
        - run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{secrets.npm_token}}
